ARG BASE_IMAGE=rocm/vllm-dev:base
FROM ${BASE_IMAGE}

ARG UID
ARG GID
ARG RENDER_GID
ARG USERNAME
ARG PYTORCH_ROCM_ARCH=gfx942
ARG TORCH_CUDA_ARCH_LIST=9.0

RUN addgroup --gid $GID $USERNAME
RUN if command -v rocm-smi ; then grep render:x /etc/group && perl -p -i -e "s/^render:x:[0-9]+/render:x:${RENDER_GID}/g" /etc/group || echo ; fi
RUN if command -v rocm-smi ; then grep render:x:$RENDER_GID /etc/group || addgroup --gid $RENDER_GID render ; fi
RUN adduser --disabled-password --gid $GID --uid $UID --gecos '' $USERNAME
RUN adduser $USERNAME sudo
RUN if command -v rocm-smi ; then adduser $USERNAME render ; fi
RUN echo "$USERNAME    ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME
RUN rm -f $(which sccache)
ARG BASE_IMAGE
RUN echo ${BASE_IMAGE} > /home/$USERNAME/.base_image

USER $USERNAME
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
COPY bundle.tgz /home/$USERNAME/bundle.tgz
RUN sudo apt update && sudo apt install -y tmux zsh less curl bc vim psmisc htop language-pack-en wget && sudo update-locale && \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended && \
    cd $HOME && tar xf bundle.tgz
COPY requirements-lint.txt /home/$USERNAME
RUN sudo pip uninstall -y pillow fsspec \
    && pip install -r /home/$USERNAME/requirements-lint.txt && pip install simple_term_menu setuptools_scm
ENV PYTORCH_ROCM_ARCH=${PYTORCH_ROCM_ARCH}
ENV TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST}
RUN sudo chown -R ${USERNAME}:${USERNAME} /usr/local/lib/python3.12/dist-packages/aiter || true
RUN sudo chown -R ${USERNAME}:${USERNAME} /usr/local/lib/python3.12/dist-packages/aiter_meta || true

COPY Dockerfile.vllm /home/$USERNAME/
COPY .gdbinit /home/$USERNAME/
CMD ["/usr/bin/zsh"]
